# Generated by Django 5.0.6 on 2024-07-19 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_song_song_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
