# Generated by Django 5.0.6 on 2024-07-19 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
